### ISSUE TITLE
Color-Options?

### ISSUE THREAD

**Issue by TheStormbringer** [sheyabernstein/MMM-connection-status#14]
Hey folks,

i was just thinking that it would be lovely if modules with come with configurable color options for output of the current status.
Like:

- Connected: #5c5c5c (dark grey)

- Not Connected: fff (white) (or f00 for red?)

I am still new to MagicMirror, so I can't implement this feature (yet). But what do you think?

**Comment by mirrormonark** [comment]
if not connected ... color is red.. fantastic
