### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by Benchington** [sheyabernstein/MMM-connection-status#16]
Is it possible to set the text size smaller?

**Comment by sheyabernstein** [comment]
You can add custom css by following the MagicMirror docs [here](https://docs.magicmirror.builders/modules/customcss.html) with a font-size rule for `.module.MMM-connection-status`

**Comment by mirrormonark** [comment]
hello, i try your comments.. but unfortunately in the suggestion it refers to weather or you have colors... can you give an example for your module so that we can understand it better? for me.. I am a beginner and newbie
