### ISSUE TITLE
add translate IT

### ISSUE THREAD

**Issue by mirrormonark** [sheyabernstein/MMM-connection-status#21]
{
	"INET_CONN_CONNECTED": "Internet è connesso",
	"INET_CONN_NOTCONNECTED": "Internet non è connesso",

	"TXT_INET_CONN": "CONNESSIONE INTERNET",
	"TXT_INET_CONN_DESC": "visualizzare lo stato della connessione a Internet"
}

**Comment by sheyabernstein** [comment]
Closed in #22
