### ISSUE TITLE
Screenshot!

### ISSUE THREAD

**Issue by E3V3A** [sheyabernstein/MMM-connection-status#4]
Please add a screenshot on how the module look when properly loaded.

**Comment by sheyabernstein** [comment]
Hi @E3V3A , what seems to be the issue?

**Comment by henrikra** [comment]
He means you should add screenshot of this module to README :D

**Comment by acejacek** [comment]
![screenshot 2019-03-03 at 22 41 30](https://user-images.githubusercontent.com/3652142/53702286-952ca380-3e05-11e9-83ed-9d6b7c761525.png)

Add this to README.md

**Comment by sheyabernstein** [comment]
hi @acejacek please create a PR. Thanks!
