### ISSUE TITLE
Error while installing MMM-connection-status

### ISSUE THREAD

**Issue by banerjeearin** [sheyabernstein/MMM-connection-status#5]
While installing the above following error are encountered:
pi@raspberrypi:~/MagicMirror/modules/MMM-connection-status $ npm install
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! file /home/pi/MagicMirror/modules/MMM-connection-status/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in array at 11:3
npm ERR!   ],
npm ERR!   ^
npm ERR! File: /home/pi/MagicMirror/modules/MMM-connection-status/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-connection-status/npm-debug.log

Kindly help

**Comment by banerjeearin** [comment]
still not got an answer

**Comment by banerjeearin** [comment]
Can you tell me what Is the resolution given .

**Comment by sheyabernstein** [comment]
@banerjeearin there was a trailing comma in package.json. It has now been removed and should work

**Comment by banerjeearin** [comment]
Thanks let me check and come back to you
